name: jnr_app
description: "Trackr: A Habit Tracking App."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.14.0
  google_fonts: ^6.1.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#111"
  android_gravity: center
  ios_content_mode: center
  image: lib/assets/logo.png
  android_12:
    image: lib/assets/logo.png
    icon_background_color: "#111"

flutter:
  uses-material-design: true

  assets:
  - lib/assets/confetti.json

  fonts:
    - family: Aldrich
      fonts:
        - asset: lib/fonts/Aldrich-Regular.ttf

