// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf3a7TnxxDmMnGNdvIBJRb9GsDSHvmjJc',
    appId: '1:512580887099:web:437dbf1ecb4bb8041df21e',
    messagingSenderId: '512580887099',
    projectId: 'trackr-4e055',
    authDomain: 'trackr-4e055.firebaseapp.com',
    storageBucket: 'trackr-4e055.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFB_oq408TJFDUk3UOIURyOCxtZ3MZhyQ',
    appId: '1:512580887099:android:5b65a0041a795ffd1df21e',
    messagingSenderId: '512580887099',
    projectId: 'trackr-4e055',
    storageBucket: 'trackr-4e055.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMFuESVvHTTCmX_-sOiUQuPnJvtT8nNtk',
    appId: '1:512580887099:ios:62c1396f47692b301df21e',
    messagingSenderId: '512580887099',
    projectId: 'trackr-4e055',
    storageBucket: 'trackr-4e055.firebasestorage.app',
    iosBundleId: 'com.example.jnrApp',
  );
}
